f = open("C:\\Users\\hp\\Desktop\\1.txt","rb")
content = f.read().decode("gb2312")
print(content)
print(len(content))
print(content.replace("\n",""))
print(content.replace("2012","2013"))
a = int(len(content)/2)
s = content[a:a+5]
print(s)
print(content[-2:0])
print(content[:11])
f1 = open("C:\\Users\\hp\\Desktop\\1.txt","w")
inf = content.replace("2012","2013")
f1.write(inf)
f1.close()
f.close()
